app:
  name: 'comic-searcher'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'

app:
  source_url: https://xkcd.com
  parallel: 10

http:

db:
  db_file: database.jsonl

sqlite:
  dsn: 

search:
  index_file: index.json